import Head from "next/head";
import styles from "../styles/Home.module.css";
import Projects from '../components/Projects'
import Footer from "../components/Footer";
import AboutMe from '../components/AboutMe'
import Hero from '../components/Hero'
import userData from "../constants/data";
import Navbar from '../components/Navbar'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Carlos Pineda</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://cdn-icons-png.flaticon.com/512/73/73443.png" />
      </Head>

        <Navbar />
        <Hero />
        <AboutMe />
        <Projects />
        <Footer />
    
    </div>
  )
}
